version: "2.1"

services:
  lnmp:
    build:
      context: ./docker/lnmp
      args:
        - local_host_ip=${LOCAL_HOST_IP}
    environment:
      - LOCAL_HOST_IP=${LOCAL_HOST_IP}
      - MYSQL_ROOT_PASSWORD=123456
    extra_hosts:
      - "${WEBSITE_DOMAIN}:${LOCAL_HOST_IP}"
    ports:
      - "80:80"
      - "220:22"
      - "6379:6379"
    links:
      - "mysql"
    volumes:
      - ${ROOT_PATH}/log/nginx:/data/nginxlogs
      - ${ROOT_PATH}/log/php:/data/phplogs
      - ${CODE_PATH}:/data/wwwroot
    tty: true

  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ${ROOT_PATH}/mysql/data:/var/lib/mysql

#  redis:
#    build: ./docker/redis
#    ports:
#      - "6379:6379"



