version: "2.1"

services:
  lnmp:
    build:
      context: ./docker/lnmp
      args:
        - local_host_ip=${LOCAL_HOST_IP}
        - website_domain=${WEBSITE_DOMAIN}
        - nginx_port=${NGINX_PORT}
        - wwwroot_path=/data/wwwroot
    environment:
      - LOCAL_HOST_IP=${LOCAL_HOST_IP}
      - MYSQL_ROOT_PASSWORD=123456
    extra_hosts:
      - "pma.com:${LOCAL_HOST_IP}"
      - "xhprof.com:${LOCAL_HOST_IP}"
      - "${WEBSITE_DOMAIN}:${LOCAL_HOST_IP}"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
      - "${SWOOLE_HTTP_PORT}:${SWOOLE_HTTP_PORT}"
      - "${SWOOLE_TCP_PORT}:${SWOOLE_TCP_PORT}"
      - "220:22"
      - "6379:6379"
    links:
      - mysql:mysqlhost
    volumes:
      - ${ROOT_PATH}/log/nginx:/data/nginxlogs
      - ${ROOT_PATH}/log/php:/data/phplogs
      - ${ROOT_PATH}:/data/wwwroot
    tty: true

  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ${ROOT_PATH}/mysql/data:/var/lib/mysql

#  redis:
#    build: ./docker/redis
#    ports:
#      - "6379:6379"



